import { useState } from 'react';

import styles from '../page.module.css';
import { renderFieldMeta, type SlugStepProps } from '../pageWizardShared';

export default function SlugStep({
  groomEnglishName,
  brideEnglishName,
  setGroomEnglishName,
  setBrideEnglishName,
  slugInput,
  setSlugInput,
  autoGeneratedSlug,
  normalizedSlugInput,
  persistedSlug,
  previewSlug,
  showClientPasswordField,
  clientPassword,
  setClientPassword,
}: SlugStepProps) {
  const [isClientPasswordVisible, setIsClientPasswordVisible] = useState(true);

  return (
    <div className={styles.fieldGrid}>
      <div className={styles.summaryCard}>
        <span className={styles.summaryLabel}>이 단계에서 하는 일</span>
        <strong className={styles.summaryValue}>영문 이름을 기준으로 청첩장 주소를 먼저 정합니다.</strong>
        <p className={styles.sectionText}>
          영문 이름을 입력하면 주소 입력칸이 자동으로 채워지고, 필요하면 주소를 직접 수정할 수
          있습니다.
        </p>
      </div>

      <div className={styles.twoColumnGrid}>
        <label className={styles.field}>
          {renderFieldMeta(
            '예비 신랑 이름(영문)',
            persistedSlug ? 'optional' : 'required',
            persistedSlug
              ? '기존 주소에서 가져온 영문 표기입니다.'
              : '영문 이름을 입력하면 주소 입력칸이 자동으로 채워집니다.'
          )}
          <input
            className={styles.input}
            value={groomEnglishName}
            placeholder="kim-shinlang"
            onChange={(event) => setGroomEnglishName(event.target.value)}
            disabled={Boolean(persistedSlug)}
          />
        </label>
        <label className={styles.field}>
          {renderFieldMeta(
            '예비 신부 이름(영문)',
            persistedSlug ? 'optional' : 'required',
            persistedSlug
              ? '기존 주소에서 가져온 영문 표기입니다.'
              : '영문 이름을 입력하면 주소 입력칸이 자동으로 채워집니다.'
          )}
          <input
            className={styles.input}
            value={brideEnglishName}
            placeholder="na-sinbu"
            onChange={(event) => setBrideEnglishName(event.target.value)}
            disabled={Boolean(persistedSlug)}
          />
        </label>
      </div>

      <label className={styles.field}>
        {renderFieldMeta(
          '페이지 주소',
          'required',
          persistedSlug
            ? '이미 생성된 페이지라서 주소를 수정할 수 없습니다. 같은 주소가 있으면 서버에서 중복 방지 suffix를 자동으로 붙입니다.'
            : '영문 소문자, 숫자, 하이픈(-)만 사용할 수 있습니다. 영문 이름을 입력하면 제안 주소가 자동으로 들어갑니다.'
        )}
        <input
          className={styles.input}
          value={slugInput}
          placeholder={autoGeneratedSlug || 'wedding-abc123'}
          onChange={(event) => setSlugInput(event.target.value)}
          onBlur={() => {
            if (!persistedSlug && normalizedSlugInput) {
              setSlugInput(normalizedSlugInput);
              return;
            }

            if (!persistedSlug && autoGeneratedSlug) {
              setSlugInput(autoGeneratedSlug);
            }
          }}
          disabled={Boolean(persistedSlug)}
        />
      </label>

      <div className={styles.summaryCard}>
        <span className={styles.summaryLabel}>주소 미리보기</span>
        <strong className={styles.summaryValue}>/{previewSlug}</strong>
        <p className={styles.sectionText}>
          {persistedSlug
            ? '이미 생성된 페이지라서 현재 주소가 고정되어 있습니다.'
            : '영문 이름으로 만든 제안 주소를 기준으로 초안 문서를 먼저 만들고, 이후 단계에서 다시 수정할 수 있습니다.'}
        </p>
      </div>

      {showClientPasswordField ? (
        <label className={styles.field}>
          {renderFieldMeta(
            '고객 편집 비밀번호',
            'required',
            '고객 로그인, 기존 청첩장 연결, 모바일 편집 로그인에 사용할 비밀번호를 직접 설정해 주세요.'
          )}
          <input
            className={styles.input}
            type={isClientPasswordVisible ? 'text' : 'password'}
            autoComplete="new-password"
            value={clientPassword}
            placeholder="예: wedding2026!"
            onChange={(event) => setClientPassword(event.target.value)}
          />
          <button
            type="button"
            className={styles.secondaryButton}
            onClick={() => setIsClientPasswordVisible((current) => !current)}
          >
            {isClientPasswordVisible ? '숨기기' : '보기'}
          </button>
        </label>
      ) : null}
    </div>
  );
}
