import styles from '../page.module.css';
import { renderFieldMeta, type SlugStepProps } from '../pageWizardShared';

export default function SlugStep({
  groomKoreanName,
  brideKoreanName,
  groomEnglishName,
  brideEnglishName,
  setGroomKoreanName,
  setBrideKoreanName,
  setGroomEnglishName,
  setBrideEnglishName,
  slugInput,
  setSlugInput,
  autoGeneratedSlug,
  normalizedSlugInput,
  persistedSlug,
  previewSlug,
}: SlugStepProps) {
  return (
    <div className={styles.fieldGrid}>
      <div className={styles.summaryCard}>
        <span className={styles.summaryLabel}>이 단계에서 하는 일</span>
        <strong className={styles.summaryValue}>페이지 주소에 사용할 영문 이름을 정합니다.</strong>
        <p className={styles.sectionText}>
          신랑·신부 한글 이름은 다음 단계인 기본 정보에서 입력합니다.
        </p>
      </div>

      <div className={styles.twoColumnGrid} hidden>
        <label className={styles.field}>
          {renderFieldMeta('예비 신랑 이름(한글)', 'required')}
          <input
            className={styles.input}
            value={groomKoreanName}
            placeholder="김신랑"
            onChange={(event) => setGroomKoreanName(event.target.value)}
          />
        </label>
        <label className={styles.field}>
          {renderFieldMeta('예비 신부 이름(한글)', 'required')}
          <input
            className={styles.input}
            value={brideKoreanName}
            placeholder="나신부"
            onChange={(event) => setBrideKoreanName(event.target.value)}
          />
        </label>
      </div>

      <div className={styles.twoColumnGrid}>
        <label className={styles.field}>
          {renderFieldMeta(
            '예비 신랑 이름(영문)',
            persistedSlug ? 'optional' : 'required',
            persistedSlug
              ? '기존 주소에서 가져온 영문 표기입니다.'
              : '영문 이름을 입력하면 주소 입력칸이 자동으로 채워집니다.'
          )}
          <input
            className={styles.input}
            value={groomEnglishName}
            placeholder="kim-shinlang"
            onChange={(event) => setGroomEnglishName(event.target.value)}
            disabled={Boolean(persistedSlug)}
          />
        </label>
        <label className={styles.field}>
          {renderFieldMeta(
            '예비 신부 이름(영문)',
            persistedSlug ? 'optional' : 'required',
            persistedSlug
              ? '기존 주소에서 가져온 영문 표기입니다.'
              : '영문 이름을 입력하면 주소 입력칸이 자동으로 채워집니다.'
          )}
          <input
            className={styles.input}
            value={brideEnglishName}
            placeholder="na-sinbu"
            onChange={(event) => setBrideEnglishName(event.target.value)}
            disabled={Boolean(persistedSlug)}
          />
        </label>
      </div>

      <label className={styles.field}>
        {renderFieldMeta(
          '페이지 주소',
          'required',
          persistedSlug
            ? '저장 후에는 수정이 불가능합니다. \n 동일한 URL이 이미 존재하는 경우 뒤에 중복 방지 영문이 자동으로 붙습니다.'
            : '영문 이름을 입력하면 주소가 자동으로 만들어집니다. 영문 소문자, 숫자, 하이픈만 사용할 수 있습니다.'
        )}
        <input
          className={styles.input}
          value={slugInput}
          placeholder="kim-shinlang-na-sinbu"
          onChange={(event) => setSlugInput(event.target.value)}
          onBlur={() => {
            if (!persistedSlug && normalizedSlugInput) {
              setSlugInput(normalizedSlugInput);
              return;
            }

            if (!persistedSlug && autoGeneratedSlug) {
              setSlugInput(autoGeneratedSlug);
            }
          }}
          disabled={Boolean(persistedSlug)}
        />
      </label>

      <div className={styles.summaryCard}>
        <span className={styles.summaryLabel}>주소 미리보기</span>
        <strong className={styles.summaryValue}>/{previewSlug}</strong>
        <p className={styles.sectionText}>
          {persistedSlug
            ? '이미 생성된 페이지라 주소는 고정되어 있습니다.'
            : '영문 이름을 기준으로 주소가 자동 생성되며, 이 단계를 확인하면 청첩장 문서가 먼저 생성됩니다.'}
        </p>
      </div>
    </div>
  );
}
