import { useMemo } from 'react';

import { normalizeInvitationPageSlugBase } from '@/services/invitationPageService';
import type { InvitationPageSeed } from '@/types/invitationPage';
import { resolveInvitationFeatures } from '@/lib/invitationProducts';
import type { EventTypeKey } from '@/lib/eventTypes';

import {
  applyDerivedWizardDefaults,
  buildWeddingDateObject,
  formatDateLabel,
  formatTimeLabel,
  getWizardSteps,
} from '../pageWizardData';
import {
  buildSlugFromEnglishNames,
  resolveWizardDraftSlug,
} from '../pageWizardClientUtils';

export function useWizardDerivedState({
  activeEventType,
  brideEnglishName,
  formState,
  groomEnglishName,
  initialSlug,
  persistedSlug,
  slugInput,
}: {
  activeEventType: EventTypeKey;
  brideEnglishName: string;
  formState: InvitationPageSeed | null;
  groomEnglishName: string;
  initialSlug: string | null;
  persistedSlug: string | null;
  slugInput: string;
}) {
  const invitationFeatures = useMemo(
    () => resolveInvitationFeatures(formState?.productTier, formState?.features),
    [formState?.features, formState?.productTier]
  );
  const wizardSteps = useMemo(
    () =>
      getWizardSteps({
        eventType: activeEventType,
        includeSetupSteps: !initialSlug,
        includeMusic: invitationFeatures.showMusic,
      }),
    [activeEventType, initialSlug, invitationFeatures.showMusic]
  );
  const previewFormState = useMemo(
    () => (formState ? applyDerivedWizardDefaults(formState) : null),
    [formState]
  );
  const autoGeneratedSlug = useMemo(
    () => buildSlugFromEnglishNames(groomEnglishName, brideEnglishName),
    [brideEnglishName, groomEnglishName]
  );
  const normalizedSlugInput = useMemo(
    () => normalizeInvitationPageSlugBase(slugInput),
    [slugInput]
  );
  const resolvedPersistedSlug = useMemo(
    () => resolveWizardDraftSlug(persistedSlug, formState?.slug),
    [formState?.slug, persistedSlug]
  );
  const previewSlug = resolvedPersistedSlug ?? normalizedSlugInput ?? 'new-page';
  const slugStepState = useMemo(
    () => ({
      slugInput,
      persistedSlug: resolvedPersistedSlug,
      groomKoreanName:
        activeEventType === 'first-birthday'
          ? previewFormState?.displayName ?? ''
          : previewFormState?.couple.groom.name ?? '',
      brideKoreanName: previewFormState?.couple.bride.name ?? '',
      groomEnglishName,
      brideEnglishName,
    }),
    [
      activeEventType,
      brideEnglishName,
      groomEnglishName,
      resolvedPersistedSlug,
      previewFormState,
      slugInput,
    ]
  );
  const currentWeddingSummary = useMemo(() => {
    if (!previewFormState) {
      return activeEventType === 'birthday'
        ? '파티 날짜를 아직 입력하지 않았습니다.'
        : '예식 날짜를 아직 입력하지 않았습니다.';
    }

    const weddingDate = buildWeddingDateObject(previewFormState);
    if (!weddingDate) {
      return activeEventType === 'birthday'
        ? '파티 날짜를 아직 입력하지 않았습니다.'
        : '예식 날짜를 아직 입력하지 않았습니다.';
    }

    return `${formatDateLabel(weddingDate)} ${formatTimeLabel(weddingDate)}`;
  }, [activeEventType, previewFormState]);

  return {
    wizardSteps,
    previewFormState,
    autoGeneratedSlug,
    normalizedSlugInput,
    resolvedPersistedSlug,
    previewSlug,
    invitationFeatures,
    maxGalleryImages: invitationFeatures.maxGalleryImages,
    slugStepState,
    currentWeddingSummary,
  };
}
