'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useMemo, useState } from 'react';

import { useAdmin } from '@/contexts';
import {
  appQueryKeys,
  FIFTEEN_MINUTES_MS,
  THIRTY_MINUTES_MS,
} from '@/lib/appQuery';
import {
  normalizeInvitationPageSlugBase,
} from '@/lib/invitationPageSlug';
import {
  DEFAULT_INVITATION_THEME,
  getInvitationThemeLabel,
  getSelectableInvitationThemeKeys,
} from '@/lib/invitationThemes';
import {
  createOwnedCustomerEvent,
} from '@/services/customerEventService';
import { getCustomerWalletSnapshot } from '@/services/customerWalletService';
import type { CustomerWalletSummary } from '@/types/customerWallet';
import type {
  InvitationProductTier,
  InvitationThemeKey,
} from '@/types/invitationPage';

import styles from '../page.module.css';

const PRODUCT_TIERS: InvitationProductTier[] = ['standard', 'deluxe', 'premium'];

function getAvailablePageCreationTiers(wallet: CustomerWalletSummary | null | undefined) {
  if (!wallet) {
    return [];
  }

  return PRODUCT_TIERS.filter((tier) => wallet.pageCreationCredits[tier] > 0);
}

function buildSlugBaseFromEnglishNames(groomEnglishName: string, brideEnglishName: string) {
  return normalizeInvitationPageSlugBase(
    [groomEnglishName.trim(), brideEnglishName.trim()].filter(Boolean).join('-')
  );
}

export default function CreateInvitationClient() {
  const { authUser, isLoggedIn, isAdminLoading } = useAdmin();
  const router = useRouter();
  const queryClient = useQueryClient();
  const [groomName, setGroomName] = useState('');
  const [brideName, setBrideName] = useState('');
  const [groomEnglishName, setGroomEnglishName] = useState('');
  const [brideEnglishName, setBrideEnglishName] = useState('');
  const [slugBase, setSlugBase] = useState('');
  const [hasManualSlugOverride, setHasManualSlugOverride] = useState(false);
  const [password, setPassword] = useState('');
  const [productTier, setProductTier] = useState<InvitationProductTier>('standard');
  const [defaultTheme, setDefaultTheme] =
    useState<InvitationThemeKey>(DEFAULT_INVITATION_THEME);
  const [notice, setNotice] = useState('');
  const selectableThemes = useMemo(() => getSelectableInvitationThemeKeys(), []);

  const walletQuery = useQuery<CustomerWalletSummary>({
    queryKey: appQueryKeys.customerWallet(authUser?.uid ?? null),
    enabled: !isAdminLoading && isLoggedIn && Boolean(authUser?.uid),
    queryFn: async () => getCustomerWalletSnapshot(authUser?.uid ?? ''),
    staleTime: FIFTEEN_MINUTES_MS,
    gcTime: THIRTY_MINUTES_MS,
    refetchOnWindowFocus: false,
  });
  const wallet = walletQuery.data ?? null;
  const walletErrorMessage =
    walletQuery.error instanceof Error ? walletQuery.error.message : '';
  const operationTicketBalance = wallet?.operationTicketBalance ?? 0;
  const availableTiers = useMemo(
    () => getAvailablePageCreationTiers(wallet),
    [wallet]
  );
  const pageCreationCreditTotal = availableTiers.reduce(
    (sum, tier) => sum + (wallet?.pageCreationCredits[tier] ?? 0),
    0
  );
  const autoGeneratedSlug = useMemo(
    () => buildSlugBaseFromEnglishNames(groomEnglishName, brideEnglishName),
    [brideEnglishName, groomEnglishName]
  );

  useEffect(() => {
    const firstTier = availableTiers[0];
    if (firstTier && !availableTiers.includes(productTier)) {
      setProductTier(firstTier);
    }
  }, [availableTiers, productTier]);

  useEffect(() => {
    if (hasManualSlugOverride) {
      return;
    }

    setSlugBase(autoGeneratedSlug);
  }, [autoGeneratedSlug, hasManualSlugOverride]);

  const createMutation = useMutation({
    mutationFn: async () =>
      createOwnedCustomerEvent({
        slugBase,
        groomName,
        brideName,
        groomEnglishName,
        brideEnglishName,
        password,
        productTier,
        defaultTheme,
      }),
    onSuccess: async (created) => {
      await Promise.all([
        queryClient.invalidateQueries({
          queryKey: appQueryKeys.ownedCustomerEvents(authUser?.uid ?? null),
        }),
        queryClient.invalidateQueries({
          queryKey: appQueryKeys.customerWallet(authUser?.uid ?? null),
        }),
      ]);
      router.replace(`/page-wizard/${encodeURIComponent(created.slug)}`, {
        scroll: false,
      });
    },
    onError: (error) => {
      setNotice(
        error instanceof Error
          ? error.message
          : '청첩장 생성에 실패했습니다. 잠시 후 다시 시도해 주세요.'
      );
    },
  });

  const handleSlugChange = (value: string) => {
    const normalizedValue = normalizeInvitationPageSlugBase(value);
    setSlugBase(normalizedValue);
    setHasManualSlugOverride(normalizedValue !== autoGeneratedSlug);
  };

  const handleSubmit = () => {
    setNotice('');

    if (!pageCreationCreditTotal) {
      setNotice('사용 가능한 제작권이 없습니다. 관리자에게 문의해 주세요.');
      return;
    }

    if (!groomName.trim() || !brideName.trim()) {
      setNotice('신랑과 신부 한글 이름을 모두 입력해 주세요.');
      return;
    }

    if (!groomEnglishName.trim() || !brideEnglishName.trim()) {
      setNotice('신랑과 신부 영문 이름을 모두 입력해 주세요.');
      return;
    }

    if (!slugBase.trim()) {
      setNotice('청첩장 주소를 입력해 주세요.');
      return;
    }

    if (password.trim().length < 4) {
      setNotice('페이지 비밀번호는 4자 이상으로 입력해 주세요.');
      return;
    }

    createMutation.mutate();
  };

  if (isAdminLoading || walletQuery.isLoading) {
    return (
      <main className={styles.page}>
        <div className={styles.shell}>
          <section className={styles.loading}>생성 가능 여부를 확인하는 중입니다.</section>
        </div>
      </main>
    );
  }

  if (!isLoggedIn) {
    return (
      <main className={styles.page}>
        <div className={styles.shell}>
          <section className={styles.hero}>
            <p className={styles.eyebrow}>Create Invitation</p>
            <h1 className={styles.title}>새 이벤트 만들기</h1>
            <p className={styles.description}>
              로그인 후 보유한 제작권으로 새 이벤트 페이지를 만들 수 있습니다.
            </p>
            <div className={styles.heroActions}>
              <Link className={styles.primaryButton} href="/login">
                로그인
              </Link>
              <Link className={styles.secondaryButton} href="/my-invitations">
                내 이벤트로 돌아가기
              </Link>
            </div>
          </section>
        </div>
      </main>
    );
  }

  return (
    <main className={styles.page}>
      <div className={styles.shell}>
        <section className={styles.hero}>
          <div className={styles.heroHeader}>
            <div>
              <p className={styles.eyebrow}>Create Invitation</p>
              <h1 className={styles.title}>새 이벤트 만들기</h1>
              <p className={styles.description}>
                보유한 제작권을 사용해 한글 이름과 영문 주소를 입력하고 초안 페이지를 생성합니다.
              </p>
            </div>
            <div className={styles.summaryStack}>
              <span className={styles.summaryItem}>제작권 {pageCreationCreditTotal}개</span>
              <span className={styles.summaryItem}>운영 티켓 {operationTicketBalance}장</span>
            </div>
          </div>
        </section>

        <section className={styles.section}>
          <div className={styles.sectionHeader}>
            <h2 className={styles.sectionTitle}>기본 정보</h2>
            <p className={styles.sectionDescription}>
              생성 후에는 내 이벤트 목록에서 상세 정보와 이미지를 이어서 입력할 수 있습니다.
            </p>
          </div>

          {walletErrorMessage ? <p className={styles.error}>{walletErrorMessage}</p> : null}

          {pageCreationCreditTotal > 0 ? (
            <div className={styles.formCard}>
              <div className={styles.walletCreditGrid}>
                {PRODUCT_TIERS.map((tier) => (
                  <span
                    className={
                      wallet?.pageCreationCredits[tier]
                        ? styles.walletCreditActive
                        : styles.walletCreditItem
                    }
                    key={tier}
                  >
                    {tier.toUpperCase()} {wallet?.pageCreationCredits[tier] ?? 0}
                  </span>
                ))}
              </div>

              <div className={styles.formGrid}>
                <label className={styles.field}>
                  <span>신랑 한글 이름</span>
                  <input
                    className={styles.input}
                    value={groomName}
                    onChange={(event) => setGroomName(event.target.value)}
                    placeholder="예: 김신랑"
                  />
                </label>
                <label className={styles.field}>
                  <span>신부 한글 이름</span>
                  <input
                    className={styles.input}
                    value={brideName}
                    onChange={(event) => setBrideName(event.target.value)}
                    placeholder="예: 나신부"
                  />
                </label>
                <label className={styles.field}>
                  <span>신랑 영문 이름</span>
                  <input
                    className={styles.input}
                    value={groomEnglishName}
                    onChange={(event) => setGroomEnglishName(event.target.value)}
                    placeholder="예: kim-shinlang"
                  />
                </label>
                <label className={styles.field}>
                  <span>신부 영문 이름</span>
                  <input
                    className={styles.input}
                    value={brideEnglishName}
                    onChange={(event) => setBrideEnglishName(event.target.value)}
                    placeholder="예: na-sinbu"
                  />
                </label>
                <label className={styles.field}>
                  <span>청첩장 주소</span>
                  <input
                    className={styles.input}
                    value={slugBase}
                    onChange={(event) => handleSlugChange(event.target.value)}
                    placeholder="예: kim-shinlang-na-sinbu"
                  />
                </label>
                <label className={styles.field}>
                  <span>페이지 비밀번호</span>
                  <input
                    className={styles.input}
                    value={password}
                    onChange={(event) => setPassword(event.target.value)}
                    placeholder="4자 이상 입력"
                    type="password"
                  />
                </label>
                <label className={styles.field}>
                  <span>사용할 제작권</span>
                  <select
                    className={styles.input}
                    value={productTier}
                    onChange={(event) =>
                      setProductTier(event.target.value as InvitationProductTier)
                    }
                  >
                    {availableTiers.map((tier) => (
                      <option key={tier} value={tier}>
                        {tier.toUpperCase()} 제작권 {wallet?.pageCreationCredits[tier] ?? 0}개
                      </option>
                    ))}
                  </select>
                </label>
                <label className={styles.field}>
                  <span>기본 디자인</span>
                  <select
                    className={styles.input}
                    value={defaultTheme}
                    onChange={(event) =>
                      setDefaultTheme(event.target.value as InvitationThemeKey)
                    }
                  >
                    {selectableThemes.map((theme) => (
                      <option key={theme} value={theme}>
                        {getInvitationThemeLabel(theme)}
                      </option>
                    ))}
                  </select>
                </label>
              </div>

              {notice ? (
                <p className={styles.notice} role="status">
                  {notice}
                </p>
              ) : null}

              <div className={styles.heroActions}>
                <button
                  className={styles.primaryButton}
                  type="button"
                  onClick={handleSubmit}
                  disabled={createMutation.isPending}
                >
                  {createMutation.isPending ? '생성 중' : '제작권 사용해서 만들기'}
                </button>
                <Link className={styles.secondaryButton} href="/my-invitations">
                  내 이벤트로 돌아가기
                </Link>
              </div>
            </div>
          ) : (
            <div className={styles.emptyState}>
              {walletErrorMessage
                ? '보유 제작권을 확인하지 못했습니다. 새로고침 후 다시 시도해 주세요.'
                : operationTicketBalance > 0
                  ? '운영 티켓은 보유 중이지만 새 이벤트 생성에는 제작권이 필요합니다. 관리자에게 제작권 지급을 요청해 주세요.'
                : '사용 가능한 제작권이 없습니다. 새 이벤트 생성이 필요하면 관리자에게 문의해 주세요.'}
            </div>
          )}
        </section>
      </div>
    </main>
  );
}
